# Generated by Django 3.1.7 on 2021-03-11 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='title',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='order_type',
            field=models.CharField(default='Buy', max_length=60),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='scrip_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='trade_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 38, 21, 478731)),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='trade_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
