# Generated by Django 3.1.7 on 2021-03-11 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20210311_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='trade_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 9, 52, 46, 227587)),
        ),
    ]
